/**
 * Active-state field definitions for vis-2 Collection widgets.
 *
 * @remarks
 * Defines override properties applied while a widget element is active (e.g., selected
 * slider value or the currently active button). Generated by
 * `commonFields({ groupName: 'Active', allFields: false })` at runtime and consumed by
 * SliderCollectionWidget and ButtonGroupCollectionWidget.
 * @example
 * ```typescript
 * import type { ActiveStateFieldsRxData } from 'vis-2-widgets-collection/types';
 *
 * const activeConfig: ActiveStateFieldsRxData = {
 *     iconColorActive: '#00ff00',
 *     backgroundColorActive: '#FF5722',
 *     textColorActive: '#FFFFFF'
 * };
 * ```
 */
export interface ActiveStateFieldsRxData {
    /**
     * Alias name override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in ButtonGroupCollectionWidget for displaying alternative labels in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * aliasActive: 'Active Label'
     * aliasActive: 'Currently Selected'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.alias}
     */
    aliasActive?: string;

    /**
     * Value font size override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in visAttrs "active" group (SliderCollectionWidget, ButtonGroupCollectionWidget).
     *
     * @default undefined
     * @example
     * ```typescript
     * valueSizeActive: '120%'
     * valueSizeActive: 150 // interpreted as 150%
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.valueSize}
     */
    valueSizeActive?: string | number;

    /**
     * Font size override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     *
     * @default undefined
     * @example
     * ```typescript
     * fontSizeActive: '1.5rem'
     * fontSizeActive: 18 // interpreted as 18px
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.fontSize}
     */
    fontSizeActive?: string | number;

    /**
     * Text color override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in ButtonGroupCollectionWidget for active button text color.
     *
     * @default undefined
     * @example
     * ```typescript
     * textColorActive: '#FF5722'
     * textColorActive: 'rgb(255, 87, 34)'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.textColor}
     */
    textColorActive?: string;

    /**
     * Main icon identifier for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in ButtonGroupCollectionWidget for active button icon display.
     *
     * @default undefined
     * @example
     * ```typescript
     * iconActive: 'active-icon.svg'
     * iconActive: '/icons/active.png'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.icon}
     */
    iconActive?: string;

    /**
     * Small icon identifier for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in ButtonGroupCollectionWidget for compact active icon display.
     *
     * @default undefined
     * @example
     * ```typescript
     * iconSmallActive: 'small-active.svg'
     * iconSmallActive: 'mdi-check-circle'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.iconSmall}
     */
    iconSmallActive?: string;

    /**
     * Icon size override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Frequently used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     *
     * @default undefined
     * @example
     * ```typescript
     * iconSizeActive: 150 // 150% of base size
     * iconSizeActive: '32px'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.iconSize}
     */
    iconSizeActive?: string | number;

    /**
     * Icon color override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Most frequently used Active property across Collection widgets.
     *
     * @default undefined
     * @example
     * ```typescript
     * iconColorActive: '#00ff00'
     * iconColorActive: 'rgba(0, 255, 0, 0.8)'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * Most frequently used Active-State property.
     * @see {@link CommonFieldsRxData.iconColor}
     */
    iconColorActive?: string;

    /**
     * Icon hover brightness override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in ButtonGroupCollectionWidget for hover effect brightness in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * iconHoverActive: 150 // 150% brightness on hover
     * iconHoverActive: 200 // 200% brightness on hover
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.iconHover}
     */
    iconHoverActive?: number;

    /**
     * Horizontal icon offset override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in SliderCollectionWidget for precise icon positioning. Supports CSS units (px, %, em, rem).
     *
     * @default undefined
     * @example
     * ```typescript
     * iconXOffsetActive: '10px'  // move 10px right when active
     * iconXOffsetActive: '-5%'   // move 5% left when active
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.iconXOffset}
     */
    iconXOffsetActive?: string;

    /**
     * Vertical icon offset override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in SliderCollectionWidget for precise icon positioning. Supports CSS units (px, %, em, rem).
     *
     * @default undefined
     * @example
     * ```typescript
     * iconYOffsetActive: '-10px' // move 10px up when active
     * iconYOffsetActive: '5rem'  // move 5rem down when active
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.iconYOffset}
     */
    iconYOffsetActive?: string;

    /**
     * Enable color mask for icon coloring override for active state (forces coloring for URL-based icons).
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     *
     * @remarks
     * By default, the CSS filter technique for icon coloring only applies to Base64-encoded icons.
     * When this option is enabled, the color mask is also applied to URL-based icons (e.g., '/local/icon.png').
     * This forces the CSS filter technique (drop-shadow + translateY) to work with external image resources.
     *
     * @default undefined
     * @example
     * ```typescript
     * enableIconColorMaskActive: true  // enable color mask for active icon
     * enableIconColorMaskActive: false // disable color mask for active icon
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.enableIconColorMask}
     */
    enableIconColorMaskActive?: boolean;

    /**
     * Header text override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in CollectionBase for displaying alternative header text in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * headerActive: 'Active Header'
     * headerActive: 'Currently Selected'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.header}
     */
    headerActive?: string | number;

    /**
     * Header font size override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in CollectionBase for header size in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * headerSizeActive: 20
     * headerSizeActive: '1.5rem'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.headerSize}
     */
    headerSizeActive?: number | string;

    /**
     * Footer text override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in CollectionBase for displaying alternative footer text in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * footerActive: 'Active Footer'
     * footerActive: 'Selected'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.footer}
     */
    footerActive?: string | number;

    /**
     * Footer font size override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in CollectionBase for footer size in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * footerSizeActive: 14
     * footerSizeActive: '0.9rem'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.footerSize}
     */
    footerSizeActive?: number | string;

    /**
     * Background gradient override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in CollectionBase for background gradient in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * backgroundActive: 'linear-gradient(to right, #ff0000, #00ff00)'
     * backgroundActive: 'radial-gradient(circle, #333, #000)'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.background}
     */
    backgroundActive?: string;

    /**
     * Background color override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in CollectionBase for solid background color in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * backgroundColorActive: '#FF5722'
     * backgroundColorActive: 'rgb(255, 87, 34)'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.backgroundColor}
     */
    backgroundColorActive?: string;

    /**
     * Frame background gradient override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in CollectionBase for frame background gradient in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * frameBackgroundActive: 'linear-gradient(to bottom, #000, #333)'
     * frameBackgroundActive: 'radial-gradient(ellipse, #fff, #ccc)'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.frameBackground}
     */
    frameBackgroundActive?: string;

    /**
     * Frame background color override for active state.
     * Generated by commonFields({ groupName: 'Active', allFields: false }).
     * Used in CollectionBase for frame solid background color in active state.
     *
     * @default undefined
     * @example
     * ```typescript
     * frameBackgroundColorActive: '#0288D1'
     * frameBackgroundColorActive: 'rgba(2, 136, 209, 0.8)'
     * ```
     * @remarks
     * Used in SliderCollectionWidget and ButtonGroupCollectionWidget.
     * Applied when slider value is selected or button is active.
     * @see {@link CommonFieldsRxData.frameBackgroundColor}
     */
    frameBackgroundColorActive?: string;
}
